services:
    vue_app:
        container_name: divequest.untypequicode.fr_container
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${EXTERNAL_PORT}:${INTERNAL_PORT}
        volumes:
            - .:/app
            - node_modules:/app/node_modules
            - nuxt:/app/.nuxt
            - output:/app/.output
        command: "node .output/server/index.mjs"
volumes:
    node_modules:
    nuxt:
    output:
